### ISSUE TITLE
Little streak in html generated

### ISSUE THREAD

**Issue by Jumanjii** [shannonmoeller-archive/doxit#4]
Hi, 

I don't know if you continue to maintain this (awesome) tool, but I have a strange issue.
In the generated docs, after each method, it is printed **= comment.ctx && comment.ctx.string.replace(/[^\w\d]+/g, '-')** except for the last one .
It is also printed in the dropdown menu.
I saw it too in your default template (I don't speaking jade so I don't really understand it :-s).

Do you already had this issue ?

**Comment by shannonmoeller** [comment]
Been a while since I've used this tool. I can take a quick look though.
